/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f2f4f6",
        "surface-container": "#eceef0",
        "primary": "#004ac6",
        "on-error": "#ffffff",
        "inverse-primary": "#b4c5ff",
        "on-primary-fixed-variant": "#003ea8",
        "primary-fixed-dim": "#b4c5ff",
        "on-secondary-container": "#5c647a",
        "surface-bright": "#f7f9fb",
        "error": "#ba1a1a",
        "outline": "#737686",
        "surface-variant": "#e0e3e5",
        "surface-dim": "#d8dadc",
        "background": "#f7f9fb",
        "on-secondary-fixed": "#131b2e",
        "tertiary-fixed-dim": "#bcc7de",
        "secondary-container": "#dae2fd",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#dae2fd",
        "surface-container-high": "#e6e8ea",
        "secondary": "#565e74",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#eeefff",
        "on-surface": "#191c1e",
        "on-error-container": "#93000a",
        "primary-container": "#2563eb",
        "on-primary-fixed": "#00174b",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eff1f3",
        "secondary-fixed-dim": "#bec6e0",
        "on-surface-variant": "#434655",
        "primary-fixed": "#dbe1ff",
        "outline-variant": "#c3c6d7",
        "tertiary": "#4b566a",
        "tertiary-container": "#636e83",
        "surface-tint": "#0053db",
        "on-tertiary-fixed-variant": "#3c475a",
        "on-background": "#191c1e",
        "on-secondary-fixed-variant": "#3f465c",
        "tertiary-fixed": "#d8e3fb",
        "surface-container-highest": "#e0e3e5",
        "error-container": "#ffdad6",
        "surface": "#f7f9fb",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#111c2d",
        "on-tertiary-container": "#ecf1ff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "md": "16px",
        "sm": "8px",
        "gutter": "24px",
        "margin-edge": "32px",
        "xs": "4px",
        "lg": "24px",
        "xl": "40px",
        "container-max": "1440px",
        "unit": "4px"
      },
      fontFamily: {
        "sans": ["Inter", "var(--font-inter)", "ui-sans-serif", "system-ui", "sans-serif"],
        "display": ["Space Grotesk", "sans-serif"],
        "label-md": ["Inter", "var(--font-inter)", "sans-serif"],
        "h1": ["Inter", "var(--font-inter)", "sans-serif"],
        "body-sm": ["Inter", "var(--font-inter)", "sans-serif"],
        "label-sm": ["Inter", "var(--font-inter)", "sans-serif"],
        "body-lg": ["Inter", "var(--font-inter)", "sans-serif"],
        "h2": ["Inter", "var(--font-inter)", "sans-serif"],
        "h3": ["Inter", "var(--font-inter)", "sans-serif"],
        "body-md": ["Inter", "var(--font-inter)", "sans-serif"],
      },
      fontSize: {
        "label-md": ["14px", {"lineHeight": "1", "letterSpacing": "0.02em", "fontWeight": "600"}],
        "h1": ["36px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-sm": ["14px", {"lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400"}],
        "label-sm": ["12px", {"lineHeight": "1", "letterSpacing": "0.04em", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400"}],
        "h2": ["30px", {"lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "h3": ["24px", {"lineHeight": "1.4", "letterSpacing": "0", "fontWeight": "600"}],
        "display": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400"}]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
